name: aidating
description: A mobile and web dating application built with Flutter and Firebase.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true

  assets:
    - _redirects
    - assets/images/
    - assets/icons/
    - assets/audio/