name: BlindAIDating # IMPORTANT: Replace 'your_app_name' with a unique name for your Flutter app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versions here: https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versions here:
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust this to your Dart SDK version if different

dependencies:
  flutter:
    sdk: flutter
  # Add any other Flutter packages your app uses here, e.g.:
  # cloud_firestore: ^4.0.0
  # firebase_auth: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Or your preferred linter version

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # For details regarding assets in packages, see https://flutter.dev/assets-and-images/#from-packages

  # An image asset can be specified here, to be used as the application icon on Android and iOS.
  # To automatically generate a custom app icon, go to https://flutter.dev/docs/development/tools/misc/icons
  # flutter_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/app_icon.png"

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the Icons class
  # in the Material Icons class.
  # uses-material-design: true