name: BlindAIDating # IMPORTANT: Replace 'your_app_name' with a unique name for your Flutter app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust this to your Dart SDK version if different

dependencies:
  flutter:
    sdk: flutter
  # Add any other Flutter packages your app uses here, e.g.:
  # cloud_firestore: ^4.0.0
  # firebase_auth: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Or your preferred linter version

flutter:
  uses-material-design: true # This is the correct and only place for it